addSbtPlugin("com.geirsson"      % "sbt-scalafmt"    % "0.4.10")
addSbtPlugin("com.typesafe.sbt"  % "sbt-git"         % "0.8.5")
addSbtPlugin("de.heikoseeberger" % "sbt-header"      % "1.6.0")
addSbtPlugin("com.jsuereth"      % "sbt-pgp"         % "1.0.0")
addSbtPlugin("org.xerial.sbt"    % "sbt-sonatype"    % "1.1")
addSbtPlugin("com.github.gseitz" % "sbt-release"     % "1.0.3")
addSbtPlugin("org.wartremover"   % "sbt-wartremover" % "1.2.1")
