addSbtPlugin("com.typesafe.sbt"  % "sbt-git"         % "0.8.5")
addSbtPlugin("de.heikoseeberger" % "sbt-header"      % "1.6.0")
addSbtPlugin("com.jsuereth"      % "sbt-pgp"         % "1.0.1")
addSbtPlugin("org.xerial.sbt"    % "sbt-sonatype"    % "1.1")
addSbtPlugin("com.github.gseitz" % "sbt-release"     % "1.0.4")
addSbtPlugin("org.wartremover"   % "sbt-wartremover" % "1.2.1")
addSbtPlugin("org.scalariform"   % "sbt-scalariform" % "1.6.0")
